# Generated by Django 5.2 on 2025-05-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlresult',
            name='books',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
